### ISSUE TITLE
Invoice record duplicated?

### ISSUE THREAD

**Issue by AiQLee** [corda/LetterOfCredit#10]
Hi, Sorry for asking again.
After I create the invoice, the record began duplicating itself in the seller and buyer page.
Is it a bug?
And I can't apply for LC in seller page.
<img width="831" alt="screen shot 2018-06-01 at 2 43 01 pm" src="https://user-images.githubusercontent.com/3413046/40823451-3fcbe3a2-65ab-11e8-98da-d647acee745b.png">
<img width="826" alt="screen shot 2018-06-01 at 2 49 50 pm" src="https://user-images.githubusercontent.com/3413046/40823452-3ff31be8-65ab-11e8-935c-428d6e146b41.png">

**Comment by AiQLee** [comment]
This problem happens in the Safari browser. When I switch to Google Chrome, the application works fine.

**Comment by CaisR3** [comment]
Thanks for highlighting, this is fixed now
