### ISSUE TITLE
Invoice can't be created

### ISSUE THREAD

**Issue by AiQLee** [corda/LetterOfCredit#9]
<img width="1129" alt="screen shot 2018-06-01 at 1 39 27 pm" src="https://user-images.githubusercontent.com/3413046/40822118-a51d0a70-65a5-11e8-9530-e9ef5d142959.png">

Hi, I run the code and try to test it.
1.I don't know how to start by issuing yourself some cash using the Issue cash URL which is /api/loc/issue-cash on your node.   I think we don't need to issue money in this demo?
Or what should be the localhost:XXXXX/api/loc/issue-cash？

2.I tried to create invoice in the exporter's node. But it keep waiting and doesn't give a result. Anyone know what's wrong with it?

**Comment by AiQLee** [comment]
Never mind. I got this problem when I ran it in the terminal.
By using IntelliJ, everything works fine.

**Comment by CaisR3** [comment]
Grab the latest, a lot has changed and it should all be working :)
